### ISSUE TITLE
Charts disappearing/resizing when switching views

### ISSUE THREAD

**Issue by klebercsilva** [extent-framework/extentreports#11]
I have been facing an issue related to the charts. They stop displaying after one clicks on any category available on the Category View, clicks back on Dashboard view and then again on another category.

Now, as you switch between the Test View and Dashboard View they start to increase in size gradually, as you can see down below.

![TestView when issue occurs]
(https://i.imgur.com/a4F1Fri.png)

![Dashboard - 1st click]
(https://i.imgur.com/t3p9Ur2.png)

![Dashboard - 2nd click]
(https://i.imgur.com/cG316Bg.png)

![Dashboard - 3rd click]
(https://i.imgur.com/u1OU0CH.png)

![Dashboard - 4th click]
(https://i.imgur.com/XX3ZEMO.png)

**Comment by anshooarora** [comment]
This was a bug in jQuery.  Upgraded to version 3.3.1.  Issue has been resolved.
