### ISSUE TITLE
[feature request] Add possibility to scale down screenshots attached to the report(s)

### ISSUE THREAD

**Issue by rcirmira** [extent-framework/extentreports#15]
At the moment ScreenShot provides following HTML using getSource()
```
 public String getSource() {
        if (getBase64String() != null)
            return "<br/><a href='" + getScreenCapturePath() + "' data-featherlight='image'><span class='label grey white-text'>base64-img</span></a>";

        return "<img class='r-img' onerror='this.style.display=\"none\"' data-featherlight='" + getScreenCapturePath() + "' src='" + getScreenCapturePath() + "' data-src='" + getScreenCapturePath() + "'>";
    }
```

It would be great to set width and height to for example 50% to scale down the image, very useful feature when testing on high resolution screens.

Potential solution:
Add width and height properties to ScreenShot class (potentially to Media class) set it in MediaEntityBuilder via overloaded createScreenCaptureFromPath() and use it in getSource().

@anshooarora What do you think?

**Comment by anshooarora** [comment]
This is a generic implementation of the markup that displays images.  Required configuration can be performed from [code](http://extentreports.com/docs/versions/4/java/v3-html-reporter.html):

```
String css = ".r-img, td img { width: 5%; }";
htmlReporter.config().setCSS(css);
```

or via [configuration.xml](http://extentreports.com/docs/versions/4/java/v3-html-reporter.html):

```
<!-- custom styles -->
<styles>
    <![CDATA[
        .r-img, td img { width: 5%; }
    ]]>
</styles>
```
