### ISSUE TITLE
End time = Start time

### ISSUE THREAD

**Issue by mmajcherczyk** [extent-framework/extentreports#6]
![test report](https://user-images.githubusercontent.com/6592592/48510229-7ead0d00-e853-11e8-877f-d19091645be7.png)
and Time Taken is 0h 0m 0s+0ms
version 4.0.1

**Comment by performrumpf** [comment]
Bug was resolved for Dashboard, but not for tests.

![test_0s_time](https://user-images.githubusercontent.com/39511399/50082173-94b24280-01f0-11e9-9d7e-93a9540b4734.png)

Bug tested in v4.0.6

**Comment by anshooarora** [comment]
Thank you.  I am able to reproduce.

**Comment by anshooarora** [comment]
Fix available in `extentreports:4.0.7-SNAPSHOT`. 

[link](https://oss.sonatype.org/content/repositories/snapshots/com/aventstack/extentreports/4.0.7-SNAPSHOT/)
